#pragma once

enum PRIMITIVE_TYPE
{
	PT_UNKOWN = 0,
	PT_POINT = GL_POINT,
	PT_LINE = GL_LINES,
	PT_LINE_STRIP = GL_LINE_STRIP,
	PT_TRIANGLE = GL_TRIANGLES,
	PT_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
	PT_TRIANGLE_FAN = GL_TRIANGLE_FAN
};
enum  USAGE_TYPE
{
	UT_STATIC_DRAW = GL_STATIC_DRAW,
	UT_STATIC_READ = GL_STATIC_READ,
	UT_DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
	UT_DYNAMIC_READ = GL_DYNAMIC_READ,
	UT_STREAM_DRAW = GL_STREAM_DRAW
};

